import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const mitr = Mitr({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  variable: "--font-mitr",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mitr.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
